baseurl = "https://aditya-kumar.tech/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
pagination.pagerSize = 5
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true


[outputs]
home = ["HTML", "RSS", "JSON", "Robots"]

[outputFormats.Robots]
mediaType = "text/plain"
baseName = "robots"
isPlainText = true
notAlternative = true


[params]
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Aditya Kumar"
    subtitle = "My simple Blog Portfolio"
    keywords = "SEO, Blog, SSG, Hugo, Golang"
    copyright = "Aditya Kumar"
    menuMore = "More"
    readMore = "Read"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
